Hw02 unpack string
almevik/otus-homeworks pull request #3
Opened 2020-12-15 13:50 UTC by almevik

2020-12-17 12:40 UTC, balabanovds requested changes
Хорошая работа!

Понравилось что используете enum, и код довольно приятно читать =)

Есть предложение улучшить производительность.
Также Вы не написали unit-тесты, а это -4 балла

Итого оценка 5/10

Успехов!

https://otus.ru/teacher-lk/homework/110814/9016/

2020-12-17 12:40 UTC, balabanovds commented on hw02_unpack_string/unpack.go
> +	var subStrBuilder strings.Builder
можно просто вернуть слайс строки, а не создавать strings.Builder

2020-12-17 12:40 UTC, balabanovds commented on hw02_unpack_string/unpack.go
> +	runesSubStr := []rune(strCur)[:len(strCur)-1]
а проверить длину строки?

2020-12-22 07:03 UTC, almevik commented on hw02_unpack_string/unpack.go
> +	runesSubStr := []rune(strCur)[:len(strCur)-1]
Функция getZeroCountStr переделана. Проверку на длину добавил, хотя она там не нужна. Пустую строку туда передать невозможно, будет минимум один символ.
Также добавил обработку символов переноса строки, табуляции и пробела. Добавил новые тесты.

2020-12-22 18:52 UTC, balabanovds requested changes
Хорошо что написали тесты.

Осталось разобраться со строкой.

Постарался описать в комментах. Если будут вопросы - доступен в Slack

Успехов!

2020-12-22 18:52 UTC, balabanovds commented on hw02_unpack_string/unpack.go
> +	if length < 1 {
можно упростить - не сохранять длину в переменную
```go
if len(strCur) == 0 {}
```

2020-12-22 18:52 UTC, balabanovds commented on hw02_unpack_string/unpack.go
> +	return string([]rune(strCur)[:length])
зачем Вы тут сначала преобразуете строку в слайс рун и затем обратно?
по сути, строка в Go это слайс байт, значит от слайса можно взять слайс =)

2020-12-23 09:55 UTC, balabanovds approved these changes
Отлично что разгрузили код, но можно сделать еще немного красивее

2020-12-23 09:55 UTC, balabanovds commented on hw02_unpack_string/unpack.go
> +	strBuilder strings.Builder
можно сделать еще красивее
есть такое понятие struct promotion
для примера <https://medium.com/golangspec/promoted-fields-and-methods-in-go-4e8d7aefb3e3>

2020-12-23 10:56 UTC, merged